classic: false

blocks:
  - permission
  - links
  - user
  - group
 # - inode
 # - context
  - date
  - size
  - name

color:
  when: auto
  theme: main.yaml

icons:
  when: auto
  theme: fancy
  separator: ":"

header: false
date: "+%y-%m-%d %H:%M:%S"
size: short
permission: rwx
layout: grid

total-size: false
indicators: false
# ignore-globs:

recursion:
  enabled: false
  depth: 5

sorting:
  column: name
  reverse: false
  dir-grouping: first

hyperlink: never
no-symlink: false
dereference: false
symlink-arrow: "->"
