style:
  tag:
    color: blue
  comment:
    color: white
  snippet:
    color: green

cheats:
  paths:
    - ~/.config/navi/cheats

finder:
  command: fzf
  overrides: --height 20
  overrides_var: --height 20
