[backdrop]
blur_intensity = 0.50999998860061169

[bar.default]
background_opacity = 0.4999999888241291
border_width = 1.0
capsule_thickness = 0.6699999887496233
center = [ "active_window" ]
end = [ "tray", "privacy", "group:g1", "clock", "notifications" ]
margin_edge = 0
margin_ends = 0
padding = 13
radius = 0
scale = 1.300000011920929
shadow = false
start = [ "session", "control-center", "launcher", "wallpaper", "taskbar" ]
thickness = 43
widget_spacing = 12

    [[bar.default.capsule_group]]
    border = ""
    fill = "on_secondary"
    id = "g1"
    members = [ "media", "clipboard", "network", "bluetooth", "volume", "brightness", "battery" ]
    opacity = 0.64999997615814209
    padding = 13.0

[calendar]
enabled = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 768.0
    cy = 841.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[notification]
background_opacity = 0.79999998211860657

[shell]
corner_radius_scale = 0.95000001415610313
polkit_agent = true
settings_show_advanced = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "x"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "h"
    variant = "destructive"

    [shell.shadow]
    direction = "center"

[theme]
builtin = "Gruvbox"
community_palette = "Noctalia legacy"
mode = "dark"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory_dark = "/home/kanata/pers/media/imgs/wallpapers"

[widget.active_window]
icon_size = 20

[widget.battery]
show_label = false

[widget.brightness]
capsule_fill = "on_secondary"
show_label = false

[widget.custom_button_2]
capsule = true
type = "custom_button"

[widget.custom_button_3]
type = "custom_button"

[widget.media]
album_art_only = true

[widget.network]
show_label = false

[widget.spacer_2]
length = 25
type = "spacer"

[widget.taskbar]
group_by_workspace = true
hide_empty_workspaces = true
workspace_label_placement = "inside"

[widget.taskbar_2]
group_by_workspace = true
hide_empty_workspaces = true
type = "taskbar"
workspace_label_placement = "inside"

[widget.volume]
capsule_fill = "on_secondary"
capsule_padding = 16.0
show_label = false

[widget.workspaces]
hide_when_empty = true
