#!/bin/sh

bspc monitor -d I II III

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio        0.50
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config normal_border_color   "#303030"
bspc config active_border_color   "#606060"
bspc config focused_border_color  "#44aa88"
bspc config presel_feedback_color "#4488aa"
bspc config urgent_border_color   "#aa4444"

killall -q sxhkd
killall -q picom
killall -q polybar
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x polybar > /dev/null || polybar &

## background ##
~/.fehbg
