return {
  "stevearc/aerial.nvim",
  config = function()
    require("aerial").setup {
      on_attach = function(bufnr)
        vim.keymap.set('n', '{', "<CMD>AerialPrev<CR>", { buffer = bufnr })
        vim.keymap.set('n', '}', "<CMD>AerialNext<CR>", { buffer = bufnr })
      end,
      backends = { "treesitter", "lsp", "man" },
      layout = {
        max_width = { 40, 0.2 },
        width = nil,
        min_width = 10,
        win_opts = {},
        default_direction = 'prefer_right',
        placement = 'window',
        resize_to_content = true,
        preserve_equality = false,
      },
      keymaps = {
        ['?'] = "actions.show_help",
        ['g?'] = "actions.show_help",
        ['<CR>'] = "actions.jump",
        ['<C-v>'] = "actions.jump_vsplit",
        ['<C-s>'] = "actions.jump_split",
        ['p'] = "actions.scroll",
        ['<C-j>'] = "actions.down_and_scroll",
        ['<C-k>'] = "actions.up_and_scroll",
        ['{'] = "actions.prev",
        ['}'] = "actions.next",
        ['[['] = "actions.prev_up",
        [']]'] = "actions.next_up",
        ['<ESC>'] = "actions.close",
        ['q'] = "actions.close",
        ['o'] = "actions.tree_toggle",
        ['za'] = "actions.tree_toggle",
        ['O'] = "actions.tree_toggle_recursive",
        ['zA'] = "actions.tree_toggle_recursive",
        ['l'] = "actions.tree_open",
        ['zo'] = "actions.tree_open",
        ['L'] = "actions.tree_open_recursive",
        ['zO'] = "actions.tree_open_recursive",
        ['h'] = "actions.tree_close",
        ['zc'] = "actions.tree_close",
        ['H'] = "actions.tree_close_recursive",
        ['zC'] = "actions.tree_close_recursive",
        ['zr'] = "actions.tree_increase_fold_level",
        ['zR'] = "actions.tree_open_all",
        ['zm'] = "actions.tree_decrease_fold_level",
        ['zM'] = "actions.tree_close_all",
        ['zx'] = "actions.tree_sync_folds",
        ['zX'] = "actions.tree_sync_folds",
      },
      lazy_load = true,
      disable_max_lines = 10000,
      disable_max_size = 2000000,
      filter_kind = {
        'Class',
        'Constructor',
        'Enum',
        'Function',
        'Interface',
        'Module',
        'Method',
        'Struct',
      },
      close_on_select = false,
      update_events = "TextChanged,InsertLeave",
      show_guides = true,
      guides = {
        mid_item = '├─',
        last_item = '└─',
        nested_top = '│ ',
        whitespace = '  ',
      },
      float = {
        border = 'double',
        relative = 'cursor',
      },
      nav = {
        border = 'double',
        autojump = false,
        preview = true,
        keymaps = {
          ['<CR>'] = "actions.jump",
          ['<C-v>'] = "actions.jump_vsplit",
          ['<C-s>'] = "actions.jump_split",
          ['h'] = "actions.left",
          ['l'] = "actions.right",
          ['<ESC>'] = "actions.close",
        },
      },
    }
  end,
  keys = {
    { mode = 'n', '<LEADER>aa', "<CMD>AerialToggle<CR>",       desc = "Aerial Toggle" },
    { mode = 'n', '<LEADER>af', "<CMD>AerialToggle float<CR>", desc = "Aerial Float" },
    { mode = 'n', '<LEADER>an', "<CMD>AerialNavToggle<CR>",    desc = "Aerial Nav" },
  },
}
