font_family      family="Hurmit Nerd Font"
font_size 15.0
disable_ligatures cursor
font_features none

cursor none
cursor_text_color background
cursor_shape block
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.0 0.3
cursor_trail_start_threshold 2

scrollbar never
scrollback_pager ~/.config/kitty/pager.sh INPUT_LINE_NUMBER CURSOR_LINE CURSOR_COLUMN

url_color #0088BB

visual_bell_color #990000
enable_audio_bell no
bell_on_tab "?"

active_border_color #C0C0C0
inactive_border_color #303030
bell_border_color #990000
enabled_layouts splits, stack

tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #E0E0E0
active_tab_background   #404040
active_tab_font_style   bold-italic
inactive_tab_foreground #505050
inactive_tab_background #101010
inactive_tab_font_style normal
tab_bar_background #030303
tab_bar_margin_color #909090

shell_integration no-cursor no-completions

foreground #EEEEEE
background #000000
background_opacity 0.6
dim_opacity 0.2

shell fish
editor nvim


#
# key configurations
#

# modifier key
kitty_mod ctrl+alt

# reload configuration
map kitty_mod+shift+r load_config_file

# layout management
map kitty_mod+l next_layout

# font resizing
map kitty_mod+arrowup change_font_size all +1.0
map kitty_mod+arrowdown change_font_size all -1.0
map kitty_mod+equal change_font_size all 0

# window resizing
map kitty_mod+r start_resizing_window

# scrollback
map kitty_mod+p show_scrollback

# window management
map kitty_mod+v launch --location=vsplit --cwd=current
map kitty_mod+s launch --location=hsplit --cwd=current
map kitty_mod+q close_window
map kitty_mod+j next_window
map kitty_mod+k previous_window
map kitty_mod+shift+j move_window_forward
map kitty_mod+shift+k move_window_backward

# tab management
map kitty_mod+n new_tab_with_cwd
map kitty_mod+shift+q close_tab
map kitty_mod+] next_tab
map kitty_mod+[ previous_tab
map kitty_mod+shift+] move_tab_forward
map kitty_mod+shift+[ move_tab_backward

# paste from clipboard
map kitty_mod+shift+v paste_from_clipboard

# load local configuration
include ~/.config/kitty/rc.conf
