cursor none
cursor_text_color background
url_color #0088BB
visual_bell_color #990000
active_border_color #C0C0C0
inactive_border_color #303030
bell_border_color #990000
active_tab_foreground   #E0E0E0
active_tab_background   #404040
inactive_tab_foreground #505050
inactive_tab_background #101010
tab_bar_background #030303
tab_bar_margin_color #909090
foreground #EEEEEE
background #000000
