user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.warnOnQuitShortcut", false);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.download.dir", "~/tmp");
user_pref("browser.theme.dark-private-windows", true);
user_pref("browser.tabs.hoverPreview.enabled", true);
user_pref("browser.compactmode.show", true);
user_pref("extensions.pocket.enabled", false);
//user_pref("general.useragent.override", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36");
