live_config_reload = true

[shell]
program = "/home/linuxbrew/.linuxbrew/bin/fish"
args = []

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
thickness = 0.01
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.offset]
x = 0
y = -2

[font.glyph_offset]
x = 0
y = -1

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Italic"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 5000
multiplier = 4

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "None"
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#990000'
green   = '#009900'
yellow  = '#999900'
blue    = '#0000AA'
magenta = '#990099'
cyan    = '#009999'
white   = '#AAAAAA'

[colors.bright]
black   = '#777777'
red     = '#FF0000'
green   = '#00FF00'
yellow  = '#FFFF00'
blue    = '#55FFFF'
magenta = '#FF00FF'
cyan    = '#00FFFF'
white   = '#FFFFFF'
