format = """
($container )\
($hostname )\
($shell ($shlvl ))\
($directory )\
$git_branch$git_commit$git_state$git_status$git_metrics\
$package\
$line_break\
( $username)( $sudo) $character \
"""

right_format = """
($battery )($cmd_duration )($jobs )($status )$time \
"""

continuation_prompt = '[ > ](dimmed blue)'

add_newline     = false
scan_timeout    = 30
command_timeout = 500
follow_symlinks = true


[profiles]
transient_prompt = """ $character """
transient_rprompt = """ $time """

[sudo]
symbol = '*'
style = 'bold bright-red'
format = '[$symbol]($style)'
disabled = false

[status]
symbol                = ''
success_symbol        = ''
not_executable_symbol = ''
not_found_symbol      = ''
sigint_symbol         = ''
signal_symbol         = ''
recognize_signal_code = true
map_symbol = true
pipestatus = true
pipestatus_separator = '|'
style = 'bold red'
format = '[$status](red)[([:](dimmed white)$common_meaning$signal_name)]($style)'
pipestatus_format = '[$pipestatus](dimmed white)'
disabled = false

[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 2
symbol = '+'
style = 'bold blue'
format = '[$symbol$number]($style)'
disabled = false

[time]
use_12hr = false
style = 'purple'
format = '[$time]($style)'
disabled = false

[battery]
full_symbol        = '='
charging_symbol    = '+'
discharging_symbol = '-'
unknown_symbol     = '?'
empty_symbol       = '_'
format = '[$symbol$percentage]($style)'
disabled = true

[[battery.display]]
threshold = 10
style = 'red'

[[battery.display]]
threshold = 30
style = 'yellow'

[[battery.display]]
threshold = 50
style = 'green'

[[battery.display]]
threshold = 100
style = 'bright-green'

[os]
style = 'white'
format = '[$name]($style)'
disabled = true

[container]
symbol = ''
style = 'bold dimmed blue'
format = '[$name]($style)'
disabled = false

[shell]
bash_indicator = 'bash'
fish_indicator = '[<](#ff0000)[>](#ff7700)[<](#ffff00)'
unknown_indicator = '?'
style = 'white'
format = '[$indicator]($style)'
disabled = false

[shlvl]
threshold = 2
symbol = '*'
style = 'white'
format = '[$symbol](dimmed white)[$shlvl](bold $style)'
disabled = false

[line_break]
disabled = false

[username]
show_always = false
style_user = 'green'
style_root = 'red'
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = true
style = 'dimmed green'
format = '[$ssh_symbol$hostname]($style)'
disabled = false

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = '.../'
read_only_style = 'bold red'
read_only = '#'
style = 'yellow'
format = '[$read_only]($read_only_style)[$path]($style)'
disabled = false

[git_branch]
always_show_remote = false
symbol = ''
style = 'bright-purple'
format = '[$branch(:$remote_branch)]($style)'
disabled = false

[git_commit]
commit_hash_length = 7
only_detached = true
tag_disabled = false
tag_max_candidates = 0
tag_symbol = ''
style = 'bold green'
format = '([<](dimmed white)[$hash]($style)([:](dimmed white)[$tag](bold dimmed green))[>](dimmed white))'
disabled = false

[git_state]
rebase       = 'RB'
merge        = 'MR'
revert       = 'RV'
cherry_pick  = 'CP'
bisect       = 'BI'
am           = 'AM'
am_or_rebase = 'AM/RB'
style = 'bold cyan'
format = '([{](dimmed white)[$state([:](dimmed white)[$progress_current/$progress_total](white))]($style)[}](dimmed white))'
disabled = false

[git_status]
conflicted  = '[=](bold bright-red)'
ahead       = '[↑](bright-green)'
behind      = '[↓](bright-red)'
diverged    = '[↕](bright-blue)({([↑$ahead_count](green))([↓$behind_count](red))})'
# untracked   = '[?](bright-blue)'
untracked = ''
stashed     = '[\$](bright-blue)'
staged      = '[+](bright-green)'
modified    = '[!](bright-yellow)'
renamed     = '[→](bright-yellow)'
deleted     = '[←](bright-yellow)'
up_to_date  = ''
typechanged = 't'
ignore_submodules = true
style = 'dimmed white'
format = '([\[[$all_status$ahead_behind]($style)\]]($style))'
disabled = false

[git_metrics]
only_nonzero_diffs = true
ignore_submodules = false
added_style = 'dimmed green'
deleted_style = 'dimmed red'
format = '([\([$added]($added_style)[$deleted]($deleted_style)\)](dimmed white))'
disabled = false

[character]
success_symbol = '[>](dimmed white)'
error_symbol   = '[>](dimmed red)'
vimcmd_symbol              = '[N](dimmed green)'
vimcmd_replace_one_symbol  = '[R](dimmed yellow)'
vimcmd_replace_symbol      = '[R](dimmed bright-yellow)'
vimcmd_visual_symbol       = '[V](dimmed bright-purple)'
format = '$symbol'
disabled = false

[cmd_duration]
min_time = 1_000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 30_000
style = 'italic blue'
format = '[$duration]($style)'
disabled = false

[package]
display_private = false
version_format = '$raw'
symbol = ''
style = 'bold dimmed cyan'
format = '[$version]($style)'
disabled = false
