format = '''
$username $directory $git_branch $all
 $character '''

add_newline     = false
scan_timeout    = 30
command_timeout = 500
follow_symlinks = true

[line_break]
disabled = true

[username]
show_always = true
style_user = 'green'
style_root = 'red'
format = '[$user]($style)'
disabled = false

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = '.../'
read_only_style = 'red'
read_only = '#'
style = 'bold yellow'
format = '[$read_only]($read_only_style)[$path]($style)'
disabled = false

[git_branch]
always_show_remote = false
symbol = '@'
format = '[$symbol$branch(:$remote_branch)]($style)'
disabled = false

[character]
success_symbol = '[>](bold black)'
error_symbol   = '[>](bold red)'
format = '$symbol'
disabled = false

[cmd_duration]
min_time = 1_000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 30_000
style = 'italic blue'
format = '[$duration]($style)'
disabled = false
