#!/bin/sh
set -eu

printf "#[fg=#eeeeee,bg=#444444,bold]"

printf "#{?client_prefix,"

printf "#[bg=#00aaee]#[fg=#eeeeee]"
printf "#{prefix}"
printf "#[bg=#444444]"

printf ",}"


printf "#{?pane_synchronized,"

printf "#[bg=#00ee00]#[fg=#eeeeee]"
printf "sync"
printf "#[bg=#444444]"

printf ",}"


printf "#{?pane_in_mode,"

printf "#[bg=#eeaa00]#[fg=#eeeeee]"
printf "mode"
printf "#[bg=#444444]"

printf ",}"

bat_capacity="$(get_battery_info "capacity")"
bat_status="$(get_battery_info "status")"

case "$bat_status" in
    "Full" )
      bat_status_symbol="~"
      ;;
    "Charging" )
      bat_status_symbol="+"
      ;;
    "Discharging" )
      bat_status_symbol="-"
      ;;
    "Not charging" )
      bat_status_symbol="="
      ;;
    * )
      bat_status_symbol="?"
      ;;
esac

printf " bat$bat_status_symbol$bat_capacity%%"

printf " mem:"
get_mem_rate
printf "%%"

printf " $(date "+%H:%M:%S") "
