#!/bin/sh
set -eu

printf "#[fg=#eeeeee,bg=#444444,bold]"

printf "#{?client_prefix,"

printf "#[bg=#00aaee]#[fg=#eeeeee]"
printf "#{prefix}"
printf "#[bg=#444444]"

printf ",}"


printf "#{?pane_synchronized,"

printf "#[bg=#00ee00]#[fg=#eeeeee]"
printf "sync"
printf "#[bg=#444444]"

printf ",}"


printf "#{?pane_in_mode,"

printf "#[bg=#eeaa00]#[fg=#eeeeee]"
printf "mode"
printf "#[bg=#444444]"

printf ",}"


bat_path="$(find /sys/class/power_supply | grep BAT)"

bat_capacity="$(cat "$bat_path/capacity")"
bat_status="$(cat "$bat_path/status")"

case "$bat_status" in
    "Full" )
      bat_status_symbol="~"
      ;;
    "Charging" )
      bat_status_symbol="+"
      ;;
    "Discharging" )
      bat_status_symbol="-"
      ;;
    "Not charging" )
      bat_status_symbol="="
      ;;
    * )
      bat_status_symbol="?"
      ;;
esac

printf " bat$bat_status_symbol$bat_capacity%%"

printf " $(awk 'BEGIN{total=0;used=0;available=0;rate=0}/^MemTotal:/{total=$2}/^MemAvailable:/{available=$2}END{used=total-available;rate=100*used/total;print "mem:"int(rate)}' /proc/meminfo)"
printf "%%"

printf " $(date "+%H:%M:%S") "
