#!/bin/sh
set -eu

window_index="#I"
pane_current_command="#{pane_current_command}"

printf "#[fg=#555599,bg=#333333]"
printf " ${window_index}"
printf " #[fg=#eeeeee,bg=#555599] "
printf "${pane_current_command} "

