script_source setup/arch/essential
script_source setup/arch/yay
script_source setup/arch/cli-tools
script_source setup/arch/virus-scanner
script_source setup/arch/niri
script_source setup/arch/greeter
script_source setup/arch/cachyos-repo
script_source setup/arch/apps
script_source setup/arch/latex
