return {
  -- Default settings,
  font = "20px monospace",
  fg   = "#fff",
  bg   = "#449",

  -- Genaral colours,
  success_fg = "#0f0",
  loaded_fg  = "#33AADD",
  error_fg = "#FFF",
  error_bg = "#F00",

  -- Warning colours,
  warning_fg = "#F00",
  warning_bg = "#FFF",

  -- Notification colours,
  notif_fg = "#444",
  notif_bg = "#FFF",

  -- Menu colours,
  menu_fg                   = "#000",
  menu_bg                   = "#fff",
  menu_selected_fg          = "#000",
  menu_selected_bg          = "#FF0",
  menu_title_bg             = "#fff",
  menu_primary_title_fg     = "#f00",
  menu_secondary_title_fg   = "#666",

  menu_disabled_fg = "#999",
  menu_disabled_bg = "#fff",
  menu_enabled_fg = "#fff",
  menu_enabled_bg = "#fff",
  menu_active_fg = "#060",
  menu_active_bg = "#fff",

  -- Proxy manager,
  proxy_active_menu_fg      = '#000',
  proxy_active_menu_bg      = '#FFF',
  proxy_inactive_menu_fg    = '#888',
  proxy_inactive_menu_bg    = '#FFF',

  -- Statusbar specific,
  sbar_fg         = "#fff",
  sbar_bg         = "#000",

  -- Downloadbar specific,
  dbar_fg         = "#fff",
  dbar_bg         = "#000",
  dbar_error_fg   = "#F00",

  -- Input bar specific,
  ibar_fg           = "#000",
  ibar_bg           = "rgba(0,0,0,0)",

  -- Tab label,
  tab_fg            = "#888",
  tab_bg            = "#222",
  tab_hover_bg      = "#292929",
  tab_ntheme        = "#ddd",
  selected_fg       = "#fff",
  selected_bg       = "#000",
  selected_ntheme   = "#ddd",
  loading_fg        = "#33AADD",
  loading_bg        = "#000",

  selected_private_tab_bg = "#3d295b",
  private_tab_bg    = "#22254a",

  -- Trusted/untrusted ssl colours,
  trust_fg          = "#0F0",
  notrust_fg        = "#F00",

  -- Follow mode hints,
  hint_font = "10px monospace, courier, sans-serif",
  hint_fg = "#fff",
  hint_bg = "#000088",
  hint_border = "1px dashed #000",
  hint_opacity = "0.3",
  hint_overlay_bg = "rgba(255,255,153,0.3)",
  hint_overlay_border = "1px dotted #000",
  hint_overlay_selected_bg = "rgba(0,255,0,0.3)",
  hint_overlay_selected_border = "1px dotted #000",

  -- General colour pairings,
  ok = { fg = "#000", bg = "#FFF" },
  warn = { fg = "#F00", bg = "#FFF" },
  error = { fg = "#FFF", bg = "#F00" },

  -- Gopher page style (override defaults),
  gopher_light = { bg = "#E8E8E8", fg = "#17181C", link = "#03678D" },
  gopher_dark  = { bg = "#17181C", fg = "#E8E8E8", link = "#f90" },
}
