#!/bin/sh
set -eu

printf "#[fg=#444444,bg=#222222,nobold,nounderscore,noitalics]#[fg=#eeeeee,bg=#444444,bold]"

printf "#{?client_prefix,"

printf "#[fg=#00aaee]#[bg=#444444]#[bg=#00aaee]#[fg=#eeeeee]"
printf "#{prefix}"
printf "#[fg=#00aaee]#[bg=#444444]#[fg=#eeeeee]"

printf ",}"


printf "#{?pane_synchronized,"

printf "#[fg=#00ee00]#[bg=#444444]#[bg=#00ee00]#[fg=#eeeeee]"
printf "sync"
printf "#[fg=#00ee00]#[bg=#444444]#[fg=#eeeeee]"

printf ",}"


printf "#{?pane_in_mode,"

printf "#[fg=#eeaa00]#[bg=#444444]#[bg=#eeaa00]#[fg=#eeeeee]"
printf "mode"
printf "#[fg=#eeaa00]#[bg=#444444]#[fg=#eeeeee]"

printf ",}"


bat_path="$(find /sys/class/power_supply | grep BAT)"

bat_capacity="$(get_battery_info "capacity")"
bat_status="$(get_battery_info "status")"

case "$bat_status" in
    "Full" )
      bat_status_symbol="~"
      ;;
    "Charging" )
      bat_status_symbol="+"
      ;;
    "Discharging" )
      bat_status_symbol="-"
      ;;
    "Not charging" )
      bat_status_symbol="="
      ;;
    * )
      bat_status_symbol="?"
      ;;
esac

printf " bat$bat_status_symbol$bat_capacity%%"

printf " mem:"
get_mem_rate
printf "%%"

printf " $(date "+%H:%M:%S") "
