#!/bin/sh

if ! command -v amixer > /dev/null 2>&1; then
  echo "\`amixer\` is not found." >&2
  exit 1
fi

get_volume() {
  amixer sget "$1" | awk '/Left:/ {
    match($0, /[0-9]*%/)
    printf substr($0, RSTART, RLENGTH-1)
  }'
}

is_mute() {
  amixer sget "$1" | awk '/Left:/ {
    if (match($0, /\[on\]/)) {
      printf "false"
    } else {
      printf "true"
    }
  }'
}

json() {
  amixer sget "$1" | awk '/Left:/ {
    printf "{\n"
    match($0, /[0-9]*%/)
    printf "  \"volume\": " substr($0, RSTART, RLENGTH-1) ",\n"
    if (match($0, /\[on\]/)) {
      printf "  \"mute\": false\n"
    } else {
      printf "  \"mute\": true\n"
    }
    printf "}\n"
  }'
}

case "$2" in
  ( volume )
    get_volume "$1"
    echo
    ;;
  ( mute )
    is_mute "$1"
    echo
    ;;
  ( json )
    json "$1"
    echo
esac

exit 0
