PageSize=5
EnableEmoji=True
EnableQuickPhraseEmoji=True
Choose Modifier=Alt
EnableHintByDefault=False
Hint Trigger=
One Time Hint Trigger=
UseNewComposeBehavior=True
EnableLongPress=False

[PrevCandidate]
0=Shift+Tab

[NextCandidate]
0=Tab

[LongPressBlocklist]
0=konsole
1=org.kde.konsole

