hl.config({
    general = {
        border_size = 1,
        gaps_in = 0,
        gaps_out = 0,
        gaps_workspaces = 0,
        col = {
            active_border = "rgba(907020ee)",
            inactive_border = "rgba(292999a0)",
            nogroup_border = "rgba(ffffaaff)",
            nogroup_border_active = "rgba(ffffaaff)",
        },
        layout = "dwindle",
        no_focus_fallback = false,
        hover_icon_on_border = true,
        resize_on_border = false,
        extend_border_grab_area = 15,
        allow_tearing = false,
        resize_corner = 0,
    },
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        fullscreen_opacity = 1.0,
        dim_inactive = false,
        dim_strength = 0.3,
        dim_special = 0.3,
        dim_around = 0.4,
        screen_shader = "",
        blur = {
            enabled = false,
            size = 8,
            passes = 1,
            ignore_opacity = false,
            new_optimizations = true,
            xray = false,
            noise = 0.0117,
            contrast = 0.9,
            brightness = 0.9,
            vibrancy = 0.1696,
            vibrancy_darkness = 0.0,
            special = true,
            popups = true,
            popups_ignorealpha = 0.2,
        },
    },
    xwayland = {
        enabled = true,
        use_nearest_neighbor = true,
        force_zero_scaling = true,
    },
    render = {
        direct_scanout = false,
    },
    opengl = {
        nvidia_anti_flicker = true,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        col = {
            splash = "0xffffff",
        },
        font_family = "Sans",
        splash_font_family = "[[Empty]]",
        force_default_wallpaper = -1,
        vrr = 0,
        mouse_move_enables_dpms = false,
        key_press_enables_dpms = false,
        always_follow_on_dnd = true,
        layers_hog_keyboard_focus = true,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        disable_autoreload = true,
        enable_swallow = false,
        swallow_regex = "[[Empty]]",
        swallow_exception_regex = "[[Empty]]",
        focus_on_activate = false,
        mouse_move_focuses_monitor = true,
        allow_session_lock_restore = false,
        background_color = "0x111111",
        close_special_on_empty = true,
        exit_window_retains_fullscreen = false,
        initial_workspace_tracking = 1,
        middle_click_paste = true,
    },
    input = {
        kb_model = "",
        kb_layout = "us",
        kb_variant = "",
        kb_options = "",
        kb_rules = "",
        kb_file = "",
        numlock_by_default = false,
        resolve_binds_by_sym = false,
        repeat_rate = 50,
        repeat_delay = 250,
        sensitivity = -0.6,
        force_no_accel = false,
        left_handed = false,
        scroll_points = "",
        scroll_method = "",
        scroll_button = 0,
        scroll_button_lock = false,
        scroll_factor = 1.0,
        natural_scroll = false,
        follow_mouse = 2,
        mouse_refocus = true,
        float_switch_override_focus = 1,
        special_fallthrough = false,
        off_window_axis_events = 1,
        emulate_discrete_scroll = 1,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = false,
            scroll_factor = 1.0,
            middle_button_emulation = false,
            tap_button_map = "[[Empty]]",
            clickfinger_behavior = false,
            tap_to_click = true,
            drag_lock = false,
            tap_and_drag = false,
        },
        touchdevice = {
            transform = 0,
            output = "[[Auto]]",
            enabled = true,
        },
        tablet = {
            transform = 0,
            output = "[[Empty]]",
            region_position = { 0, 0 },
            region_size = { 0, 0 },
            relative_input = false,
            left_handed = false,
            active_area_size = { 0, 0 },
            active_area_position = { 0, 0 },
        },
    },
    group = {
        insert_after_current = true,
        focus_removed_window = true,
        col = {
            border_active = "rgba(66ffff00)",
            border_inactive = "rgba(66777700)",
            border_locked_active = "rgba(66ff5500)",
            border_locked_inactive = "rgba(66775500)",
        },
        groupbar = {
            enabled = true,
            font_family = "[[Empty]]",
            font_size = 8,
            gradients = true,
            height = 14,
            stacked = false,
            priority = 3,
            render_titles = true,
            scrolling = true,
            text_color = "rgba(ffffffff)",
            col = {
                active = "rgba(66ffff00)",
                inactive = "rgba(66777700)",
                locked_active = "rgba(66ff5500)",
                locked_inactive = "rgba(66775500)",
            },
        },
    },
    gestures = {
        workspace_swipe_distance = 300,
        workspace_swipe_touch = false,
        workspace_swipe_invert = true,
        workspace_swipe_touch_invert = false,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
        workspace_swipe_create_new = true,
        workspace_swipe_direction_lock = true,
        workspace_swipe_direction_lock_threshold = 10,
        workspace_swipe_forever = false,
        workspace_swipe_use_r = false,
    },
    dwindle = {
        preserve_split = true,
        force_split = 2,
        smart_split = false,
        smart_resizing = true,
        permanent_direction_override = false,
        special_scale_factor = 1.0,
        split_width_multiplier = 1.0,
        use_active_for_splits = true,
        default_split_ratio = 1.0,
        split_bias = 0,
    },
    master = {
        allow_small_split = false,
        special_scale_factor = 1.0,
        mfact = 0.5,
        new_status = "slave",
        new_on_top = false,
        new_on_active = "none",
        orientation = "left",
        smart_resizing = true,
        drop_at_cursor = true,
    },
    cursor = {
        no_hardware_cursors = false,
        no_break_fs_vrr = false,
        min_refresh_rate = 24,
        hotspot_padding = 1,
        inactive_timeout = 0,
        no_warps = false,
        persistent_warps = false,
        warp_on_change_workspace = false,
        default_monitor = "[[Empty]]",
        zoom_factor = 1.0,
        zoom_rigid = false,
        enable_hyprcursor = true,
        hide_on_key_press = false,
        hide_on_touch = true,
    },
    binds = {
        pass_mouse_when_bound = false,
        scroll_event_delay = 300,
        workspace_back_and_forth = false,
        allow_workspace_cycles = false,
        workspace_center_on = 0,
        focus_preferred_method = 0,
        ignore_group_lock = false,
        movefocus_cycles_fullscreen = true,
        disable_keybind_grabbing = false,
        window_direction_monitor_fallback = true,
    },
    animations = {
        enabled = true,
    },
})
