sub-auto=fuzzy
sub-bold=yes
vo=gpu-next
gpu-api=auto
hwdec=auto
hwdec-codecs=h264,vc1,hevc,vp8,vp9,av1,prores,prores_raw,ffv1,dpx
ao=pipewire
force-window=yes
quiet=yes
script-opts=osc-timetotal=yes
keep-open=yes
