dothome "config/xdg/user-dirs.dirs" ".config/user-dirs.dirs"
. "$TARGET_PATH/.config/user-dirs.dirs"
msg_run mkdir -p -- "$XDG_DESKTOP_DIR"
msg_run mkdir -p -- "$XDG_DOWNLOAD_DIR"
msg_run mkdir -p -- "$XDG_TEMPLATES_DIR"
msg_run mkdir -p -- "$XDG_PUBLICSHARE_DIR"
msg_run mkdir -p -- "$XDG_DOCUMENTS_DIR"
msg_run mkdir -p -- "$XDG_MUSIC_DIR"
msg_run mkdir -p -- "$XDG_PICTURES_DIR"
msg_run mkdir -p -- "$XDG_VIDEOS_DIR"
msg_run mkdir -p -- "$XDG_PROJECTS_DIR"
xdg-user-dirs-update
