dothome "config/xdg/user-dirs.dirs" ".config/user-dirs.dirs"
. "$TARGET_DIR/.config/user-dirs.dirs"
! [ -d "$XDG_DESKTOP_DIR" ]     && _print_run mkdir -p -- "$XDG_DESKTOP_DIR"
! [ -d "$XDG_DOWNLOAD_DIR" ]    && _print_run mkdir -p -- "$XDG_DOWNLOAD_DIR"
! [ -d "$XDG_TEMPLATES_DIR" ]   && _print_run mkdir -p -- "$XDG_TEMPLATES_DIR"
! [ -d "$XDG_PUBLICSHARE_DIR" ] && _print_run mkdir -p -- "$XDG_PUBLICSHARE_DIR"
! [ -d "$XDG_DOCUMENTS_DIR" ]   && _print_run mkdir -p -- "$XDG_DOCUMENTS_DIR"
! [ -d "$XDG_MUSIC_DIR" ]       && _print_run mkdir -p -- "$XDG_MUSIC_DIR"
! [ -d "$XDG_PICTURES_DIR" ]    && _print_run mkdir -p -- "$XDG_PICTURES_DIR"
! [ -d "$XDG_VIDEOS_DIR" ]      && _print_run mkdir -p -- "$XDG_VIDEOS_DIR"
! [ -d "$XDG_PROJECTS_DIR" ]    && _print_run mkdir -p -- "$XDG_PROJECTS_DIR"
xdg-user-dirs-update
