#!/bin/sh
set -eu

window_index="#I"
pane_current_path="#{b:pane_current_path}"

printf "#[fg=#222222,bg=#eeeeee]#[fg=#559955,bg=#eeeeee]"
printf " ${window_index}"
printf " #[fg=#eeeeee,bg=#559955] "
printf "${pane_current_path} "
printf "#[fg=#559955,bg=#222222,nobold]"

