require "settings.options"
require "settings.disable_plugins"
require "settings.keymaps"
require "settings.autocmd"
require "settings.statusline"
require "settings.statuscolumn"
require "settings.tabline"
require "settings.highlights"
