# fcitx5
env = XMODIFIERS, @im=fcitx
env = QT_IM_MODULE, fcitx
exec-once = uwsm app -- fcitx5 -d

# ags
# exec-once = uwsm app -- ags run

# waybar
exec-once = uwsm app -- waybar

# awww
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- awww img ~/pers/imgs/wallpapers/background.png --transition-type center --transition-duration 1

# mako
exec-once = uwsm app -- mako

# wl-clipboard
exec-once = uwsm app -- wl-paste -w cliphist store

# hypridle
exec-once = pidof hypridle || uwsm app -- hypridle
