general {
    border_size = 1

    gaps_in = 0
    gaps_out = 0
    gaps_workspaces = 0

    col.active_border = rgba(907020ee)
    col.inactive_border = rgba(292999a0)
    col.nogroup_border = rgba(ffffaaff)
    col.nogroup_border_active = rgba(ffffaaff)

    layout = dwindle

    no_focus_fallback = false

    hover_icon_on_border = true

    resize_on_border = false
    extend_border_grab_area = 15

    allow_tearing = false

    resize_corner = 0
}
