#!/bin/sh
set -eu

printf "#[fg=#eeeeee,bg=#888888,bold]"

printf "#{?client_prefix,"

printf "#[bg=#00aaee]#[fg=#eeeeee]"
printf "#{prefix}"
printf "#[bg=#888888]"

printf ",}"


printf "#{?pane_synchronized,"

printf "#[bg=#00ee00]#[fg=#eeeeee]"
printf "sync"
printf "#[bg=#888888]"

printf ",}"


printf "#{?pane_in_mode,"

printf "#[bg=#eeaa00]#[fg=#eeeeee]"
printf "mode"
printf "#[bg=#888888]"

printf ",}"


printf " $(date "+%m/%d/%Y (%a) %H:%M:%S") "
